config/routes.rb
KernDist::Application.routes.draw do
  resources :devices

  resources :kerns

  get "home/index"
  root :to => "home#index"

end

app/models/device.rb
class Device
  include Mongoid::Document
  
  field :name
  key :name

  references_many :kerns
end

app/models/kern.rb
class Kern
  include Mongoid::Document
  include Mongoid::Paperclip

  field :name
  field :version, :type => Float

  has_mongoid_attached_file :kernzip

  validates_presence_of :name, :version, :kernzip

  referenced_in :device
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  	@devices = Device.all
  	@kernels = Kern.all


  end

end

app/controllers/kerns_controller.rb
class KernsController < ApplicationController
  # GET /kerns
  # GET /kerns.json
  def index
    @kerns = Kern.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kerns }
    end
  end

  # GET /kerns/1
  # GET /kerns/1.json
  def show
    @kern = Kern.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kern }
    end
  end

  # GET /kerns/new
  # GET /kerns/new.json
  def new
    @kern = Kern.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kern }
    end
  end

  # GET /kerns/1/edit
  def edit
    @kern = Kern.find(params[:id])
  end

  # POST /kerns
  # POST /kerns.json
  def create
    @kern = Kern.new(params[:kern])

    respond_to do |format|
      if @kern.save
        format.html { redirect_to @kern, notice: 'Kern was successfully created.' }
        format.json { render json: @kern, status: :created, location: @kern }
      else
        format.html { render action: "new" }
        format.json { render json: @kern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kerns/1
  # PUT /kerns/1.json
  def update
    @kern = Kern.find(params[:id])

    respond_to do |format|
      if @kern.update_attributes(params[:kern])
        format.html { redirect_to @kern, notice: 'Kern was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @kern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kerns/1
  # DELETE /kerns/1.json
  def destroy
    @kern = Kern.find(params[:id])
    @kern.destroy

    respond_to do |format|
      format.html { redirect_to kerns_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kerns_helper.rb
module KernsHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  -if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @devices.each do |device|
    %tr
      %td= device.name
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @device.name

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path

app/views/home/index.html.haml
#selectDevice
	%h1 Select Your Device

	%select
		= @devices.each do |d|
			%option= d.name

app/views/kerns/_form.html.haml
= form_for @kern do |f|
  -if @kern.errors.any?
    #error_explanation
      %h2= "#{pluralize(@kern.errors.count, "error")} prohibited this kern from being saved:"
      %ul
        - @kern.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :version
    = f.text_field :version
  .field
    = f.label :device
    = f.collection_select :device_id, Device.all, :id, :name
  .field
    = f.file_field :kernzip
  .actions
    = f.submit 'Save'

app/views/kerns/edit.html.haml
%h1 Editing kern

= render 'form'

= link_to 'Show', @kern
\|
= link_to 'Back', kerns_path

app/views/kerns/index.html.haml
%h1 Listing kerns

%table
  %tr
    %th Name
    %th Version
    %th
    %th
    %th

  - @kerns.each do |kern|
    %tr
      %td= kern.name
      %td= kern.version
      %td= link_to 'Show', kern
      %td= link_to 'Edit', edit_kern_path(kern)
      %td= link_to 'Destroy', kern, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Kern', new_kern_path

app/views/kerns/new.html.haml
%h1 New Kernel

= render 'form'

= link_to 'Back', kerns_path

app/views/kerns/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @kern.name
%p
  %b Version:
  = @kern.version
%p
  %b Link:
  = link_to 'Download', @kern.kernzip.url

= link_to 'Edit', edit_kern_path(@kern)
\|
= link_to 'Back', kerns_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KernDist
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body#main
    #container
      #banner
        = image_tag("banner.png")
      #content
        = yield
      #footer
        &copy 2011 Thebcblends